edx/edx-notifications

setup.py

@chrisndodge, pylru was not being installed, causing tests failures. Just added this  and now the tests are running fine locally.

Added pylru to the dependencies in setup.py

---

edx_notifications/openedx/course_announcements.py
edx_notifications/openedx/forums.py
edx_notifications/openedx/notification_type_registration.py
edx_notifications/server/web/static/edx_notifications/templates/renderers/course_announcements/new_announcement.html
edx_notifications/startup.py
edx_notifications/tests/test_startup.py
testserver/views.py

@chrisndodge I have added the PR for the changes in the Course update Renderer for Notification Type.

(WIP) add the new renderer for the course updates 

---

run_bokchoy_tests.sh
testserver/bokchoy_settings.py
testserver/test/acceptance/pages/logged_in_home_page.py
testserver/test/acceptance/pages/registration_page.py
testserver/test/acceptance/test_notifications.py

added a separate bokchoy_settings file which will create test_notifications db, the shell script will now use this setting file to create db and after the tests are complete the db is deleted using simple rm command

creating separate test db for bok-choy

---

testserver/test/acceptance/pages/__init__.py
testserver/test/acceptance/pages/logged_in_home_page.py
testserver/test/acceptance/pages/login_page.py
testserver/test/acceptance/pages/registration_page.py
testserver/test/acceptance/test_notifications.py

@chrisndodge ,  I have added the wait for ajax command instead of time.sleep. I have tested it on local machine and also on network, so far I haven't seen any failure. Let's see if this fixes the issue

used wait_for_ajax instead of time.sleep

---

AUTHORS

@chrisndodge i have added the team names in the Contributor's list.

added the names in the contributor's list.

---

edx_notifications/server/web/static/edx_notifications/js/views/notification_pane_view.js

@chrisndodge i have changed the title of the unread notifications tab.

changed the title of the unread notifications tab

---

edx_notifications/server/web/static/edx_notifications/js/test/spec/counter_icon_view_Spec.js
edx_notifications/server/web/static/edx_notifications/js/test/spec/notification_pane_view_Spec.js
karma.conf.js

Hi @chrisndodge ,
Please review.
I have added some jasmine tests for notification pane view.
Introduced line breaks in fixtures for readability

Jasmine tests for Notification Pane View

---

edx_notifications/server/web/static/edx_notifications/js/test/spec/notification_pane_view_Spec.js
testserver/test/acceptance/pages/__init__.py
testserver/test/acceptance/pages/logged_in_home_page.py
testserver/test/acceptance/pages/logout_page.py
testserver/test/acceptance/pages/notification_target_page.py
testserver/test/acceptance/test_notifications.py

1) Added the test to verify that clicking on a notification redirects user to a specific page (this test is a bit rough at edges as the functionality is not fully developed, currently all notifications are redirecting user to a new page and as the page is not valid, I have to use back button and then login/logout to record the after effects)
2) Added the tests to verify that clicking on notification removes it from unread notifications tab and also decreases the notification count on main page by 1.
3) Added a login function which summarises all login related statements and used this function in all tests
4) Added and modified some wait checks for slower internet connections

Additions and modifications in bok-choy tests

---

edx_notifications/server/web/templates/django/notifications_widget.html
testserver/templates/index.html

@chrisndodge here is the PR for the IE browser issues. I hope this will fix this.
I had some problem with the date.js library in the IE9. I skipped those issues and worked on the browser issues. The integration server is working fine with dates and i think this is only in my local server.

SOL-552 cross browser compatibility issue.

---

edx_notifications/server/web/static/edx_notifications/js/views/counter_icon_view.js

@chrisndodge kindly review the changes. 
- Fixed: IE9 not auto refreshing

SOL-564 IE9 not auto refreshing

---

edx_notifications/server/web/static/edx_notifications/js/views/counter_icon_view.js
edx_notifications/server/web/static/edx_notifications/js/views/notification_pane_view.js

@chrisndodge kindly review some fixes as highlighted by Kashif in edx-notifications.

bugs fixes as highlighted by Kashif in edx-notifications

---

edx_notifications/server/web/static/edx_notifications/js/views/counter_icon_view.js
edx_notifications/server/web/static/edx_notifications/js/views/notification_pane_view.js

Reverts edx/edx-notifications#98

Revert "bugs fixes as highlighted by Kashif in edx-notifications"

---

edx_notifications/lib/consumer.py
edx_notifications/lib/publisher.py
edx_notifications/server/api/consumer.py
edx_notifications/server/api/tests/test_consumer.py
edx_notifications/server/api/url_regex.py
edx_notifications/server/api/urls.py
edx_notifications/server/api/urls_mock.py

@chrisndodge Kindly review the changes.
- added the new endpoints for UserPreferences Tables.
- added the test cases for all the endpoints.

SOL-600 added HTTP endpoints for User Preferences

---

edx_notifications/stores/sql/store_provider.py
edx_notifications/stores/sql/tests/test_store_provider.py
edx_notifications/stores/store.py
edx_notifications/stores/tests/test_store.py

@chrisndodge I have created the PR against the notification digest branch.
Kindly review.
Thanks

SOL-659- created the new method for purging userNotifications.

---

edx_notifications/stores/sql/tests/test_models.py

Checking just the field names for now. Field Types are not being checked.

Added tests to match field names between SQLUserNotification and SQLUserNotificationArchive

---

requirements.txt
test_requirements.txt

Aligned edx-notifications dependencies with edx-platform to avoid version conflicts.

Aligned edx-notifications dependencies with edx-platform

---

.travis.yml
edx_notifications/channels/tests/test_urban_airship.py
edx_notifications/channels/urban_airship.py
requirements.txt
settings.py

This PR has changes to support push notifications support via Urban airship mobile backend. 
Details for the work can be found in 
https://openedx.atlassian.net/browse/YONK-729
@jawadtahir could you please review?

yonk-729: Urban airship push notification support

---

setup.py

updated version in setup

---

edx_notifications/channels/urban_airship.py
settings.py

Removed unused params in UrbanAirshipNotificationChannelProvider constructor.

removed unused params in UrbanAirshipNotificationChannelProvider constructor

---

edx_notifications/channels/tests/test_urban_airship.py
edx_notifications/channels/urban_airship.py
setup.py

Changes include addition of notification type in course announcement notification payload

YONK-837: Added notification type in course announcement payload

---

edx_notifications/stores/sql/tests/__init__.py
edx_notifications/stores/sql/tests/test_models.py
edx_notifications/stores/sql/tests/test_store_provider.py
pylintrc

file name fix and pylint issues

---

edx_notifications/channels/triggered_email.py
edx_notifications/digests.py
edx_notifications/lib/publisher.py
edx_notifications/scopes.py
edx_notifications/server/api/urls.py
edx_notifications/server/api/urls_mock.py
edx_notifications/server/urls.py
edx_notifications/server/web/templates/django/notifications_widget_header.html
edx_notifications/server/web/templates/django/notifications_widget_preferences_header.html
edx_notifications/server/web/urls.py
requirements.txt
settings.py
setup.py
test_requirements.txt
testserver/bokchoy_settings.py
testserver/settings.py
testserver/urls.py
testserver/views.py

Changes required to run edx notifications app on Django 1.11.

Django upgrade 1.11

---

edx_notifications/lib/admin.py
edx_notifications/server/api/admin.py
edx_notifications/server/api/tests/test_admin.py
edx_notifications/server/api/url_regex.py
edx_notifications/server/api/urls.py
edx_notifications/server/api/urls_mock.py
edx_notifications/stores/sql/store_provider.py
setup.py

This PR adds an API to delete notifications for specific users, along their preferences, purging PII information from the database.
**Reviewers**

Add API to purge notifications for specific users

---

.gitignore
requirements/base.txt
requirements/django.txt
requirements/testing.in
requirements/testing.txt
run_bokchoy_tests.sh
settings.py
testserver/bokchoy_settings.py
testserver/settings.py
tox.ini

**Packages removed**
- nose
- django_nose
**Packages Added**
- pytest-django

[BD-18] switch from nose to pytest

---

README.md

This PR fixes the heading in the README file.

fix heading in README file
